### Sentiment Analysis of Reuters Data

In [2]:
import pandas as pd
from nltk.sentiment import vader

In [25]:
reuters_data = pd.read_csv('../data/reuters/combined.csv')
reuters_data = reuters_data[['title','description','date']]
reuters_data

,title,description,date
0,Insurer Hartford to pay $650 million for claim...,Insurer Hartford Financial Services Group said...,2021-04-16
1,Congress poised for battle over reparations fo...,Congress poised for battle over reparations fo...,2021-04-16
2,"Knighthead, Certares sweeten bid to fund Hertz...",Investment firms Knighthead Capital Management...,2021-04-16
3,Google misled consumers over data collection -...,SYDNEY (Reuters) -Australia's federal court fo...,2021-04-16
4,"With flagship electric car, Mercedes takes fig...","Daimler AG on Thursday unveiled the electric ""...",2021-04-16
...,...,...,...
49672,Cambridge Analytica played key Trump campaign ...,The suspended chief executive of UK-based poli...,2018-03-20
49673,"Factbox: How United States, others regulate au...",An Uber self-driving sport utility vehicle str...,2018-03-20
49674,Senate Democrat wants Facebook CEO Zuckerberg ...,"U.S. Senator Dianne Feinstein, the top Democra...",2018-03-20
49675,Factbox: Who is Cambridge Analytica and what d...,British data analytics firm Cambridge Analytic...,2018-03-20
49676,UK will always consider ways to improve data l...,Britain will consider any suggestions to give ...,2018-03-20

In [9]:
# Using the default vader_lexicon.txt
import nltk
nltk.download('vader_lexicon')
analyser = vader.SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/oenmalm/nltk_data...

In [19]:
headline_sentiment = reuters_data['title'].apply(analyser.polarity_scores)
headline_sentiment

0        {'neg': 0.272, 'neu': 0.728, 'pos': 0.0, 'comp...
1        {'neg': 0.224, 'neu': 0.603, 'pos': 0.172, 'co...
2        {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
3        {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
4        {'neg': 0.236, 'neu': 0.636, 'pos': 0.127, 'co...
                               ...
49672    {'neg': 0.0, 'neu': 0.806, 'pos': 0.194, 'comp...
49673    {'neg': 0.0, 'neu': 0.741, 'pos': 0.259, 'comp...
49674    {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
49675    {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
49676    {'neg': 0.0, 'neu': 0.791, 'pos': 0.209, 'comp...
Name: title, Length: 49677, dtype: object

In [26]:
reuters_data = reuters_data.join(pd.DataFrame(headline_sentiment.to_list()), how='right')
reuters_data

,title,description,date,neg,neu,pos,compound
0,Insurer Hartford to pay $650 million for claim...,Insurer Hartford Financial Services Group said...,2021-04-16,0.272,0.728,0.000,-0.6808
1,Congress poised for battle over reparations fo...,Congress poised for battle over reparations fo...,2021-04-16,0.224,0.603,0.172,-0.1531
2,"Knighthead, Certares sweeten bid to fund Hertz...",Investment firms Knighthead Capital Management...,2021-04-16,0.000,1.000,0.000,0.0000
3,Google misled consumers over data collection -...,SYDNEY (Reuters) -Australia's federal court fo...,2021-04-16,0.000,1.000,0.000,0.0000
4,"With flagship electric car, Mercedes takes fig...","Daimler AG on Thursday unveiled the electric ""...",2021-04-16,0.236,0.636,0.127,-0.2960
...,...,...,...,...,...,...,...
49672,Cambridge Analytica played key Trump campaign ...,The suspended chief executive of UK-based poli...,2018-03-20,0.000,0.806,0.194,0.3400
49673,"Factbox: How United States, others regulate au...",An Uber self-driving sport utility vehicle str...,2018-03-20,0.000,0.741,0.259,0.4215
49674,Senate Democrat wants Facebook CEO Zuckerberg ...,"U.S. Senator Dianne Feinstein, the top Democra...",2018-03-20,0.000,1.000,0.000,0.0000
49675,Factbox: Who is Cambridge Analytica and what d...,British data analytics firm Cambridge Analytic...,2018-03-20,0.000,1.000,0.000,0.0000
49676,UK will always consider ways to improve data l...,Britain will consider any suggestions to give ...,2018-03-20,0.000,0.791,0.209,0.4404

In [ ]:
description_sentiment = reuters_data['description'].apply(analyser.polarity_scores)
reuters_data = reuters_data.join(pd.DataFrame(headline_sentiment.to_list()), how='right', rsuffix='_description')
reuters_data