### Sentiment Analysis of Reuters Data

In [1]:
import pandas as pd
from nltk.sentiment import vader

In [2]:
reuters_data = pd.read_csv('../data/reuters/combined.csv')
reuters_data = reuters_data[['title','description','date']]
reuters_data

,title,description,date
0,Insurer Hartford to pay $650 million for claim...,Insurer Hartford Financial Services Group said...,2021-04-16
1,Congress poised for battle over reparations fo...,Congress poised for battle over reparations fo...,2021-04-16
2,"Knighthead, Certares sweeten bid to fund Hertz...",Investment firms Knighthead Capital Management...,2021-04-16
3,Google misled consumers over data collection -...,SYDNEY (Reuters) -Australia's federal court fo...,2021-04-16
4,"With flagship electric car, Mercedes takes fig...","Daimler AG on Thursday unveiled the electric ""...",2021-04-16
...,...,...,...
49672,Cambridge Analytica played key Trump campaign ...,The suspended chief executive of UK-based poli...,2018-03-20
49673,"Factbox: How United States, others regulate au...",An Uber self-driving sport utility vehicle str...,2018-03-20
49674,Senate Democrat wants Facebook CEO Zuckerberg ...,"U.S. Senator Dianne Feinstein, the top Democra...",2018-03-20
49675,Factbox: Who is Cambridge Analytica and what d...,British data analytics firm Cambridge Analytic...,2018-03-20
49676,UK will always consider ways to improve data l...,Britain will consider any suggestions to give ...,2018-03-20

In [3]:
# Using the default vader_lexicon.txt
import nltk
nltk.download('vader_lexicon')
analyser = vader.SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/oenmalm/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [4]:
headline_sentiment = reuters_data['title'].apply(analyser.polarity_scores)
headline_sentiment

0        {'neg': 0.272, 'neu': 0.728, 'pos': 0.0, 'comp...
1        {'neg': 0.224, 'neu': 0.603, 'pos': 0.172, 'co...
2        {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
3        {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
4        {'neg': 0.236, 'neu': 0.636, 'pos': 0.127, 'co...
                               ...
49672    {'neg': 0.0, 'neu': 0.806, 'pos': 0.194, 'comp...
49673    {'neg': 0.0, 'neu': 0.741, 'pos': 0.259, 'comp...
49674    {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
49675    {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
49676    {'neg': 0.0, 'neu': 0.791, 'pos': 0.209, 'comp...
Name: title, Length: 49677, dtype: object

In [5]:
reuters_data = reuters_data.join(pd.DataFrame(headline_sentiment.to_list()), how='right')
reuters_data

,title,description,date,neg,neu,pos,compound
0,Insurer Hartford to pay $650 million for claim...,Insurer Hartford Financial Services Group said...,2021-04-16,0.272,0.728,0.000,-0.6808
1,Congress poised for battle over reparations fo...,Congress poised for battle over reparations fo...,2021-04-16,0.224,0.603,0.172,-0.1531
2,"Knighthead, Certares sweeten bid to fund Hertz...",Investment firms Knighthead Capital Management...,2021-04-16,0.000,1.000,0.000,0.0000
3,Google misled consumers over data collection -...,SYDNEY (Reuters) -Australia's federal court fo...,2021-04-16,0.000,1.000,0.000,0.0000
4,"With flagship electric car, Mercedes takes fig...","Daimler AG on Thursday unveiled the electric ""...",2021-04-16,0.236,0.636,0.127,-0.2960
...,...,...,...,...,...,...,...
49672,Cambridge Analytica played key Trump campaign ...,The suspended chief executive of UK-based poli...,2018-03-20,0.000,0.806,0.194,0.3400
49673,"Factbox: How United States, others regulate au...",An Uber self-driving sport utility vehicle str...,2018-03-20,0.000,0.741,0.259,0.4215
49674,Senate Democrat wants Facebook CEO Zuckerberg ...,"U.S. Senator Dianne Feinstein, the top Democra...",2018-03-20,0.000,1.000,0.000,0.0000
49675,Factbox: Who is Cambridge Analytica and what d...,British data analytics firm Cambridge Analytic...,2018-03-20,0.000,1.000,0.000,0.0000
49676,UK will always consider ways to improve data l...,Britain will consider any suggestions to give ...,2018-03-20,0.000,0.791,0.209,0.4404

In [6]:
description_sentiment = reuters_data['description'].apply(analyser.polarity_scores)
reuters_data = reuters_data.join(pd.DataFrame(description_sentiment.to_list()), how='right', rsuffix='_description')
reuters_data

,title,description,date,neg,neu,pos,compound,neg_description,neu_description,pos_description,compound_description
0,Insurer Hartford to pay $650 million for claim...,Insurer Hartford Financial Services Group said...,2021-04-16,0.272,0.728,0.000,-0.6808,0.138,0.811,0.052,-0.5423
1,Congress poised for battle over reparations fo...,Congress poised for battle over reparations fo...,2021-04-16,0.224,0.603,0.172,-0.1531,0.224,0.603,0.172,-0.1531
2,"Knighthead, Certares sweeten bid to fund Hertz...",Investment firms Knighthead Capital Management...,2021-04-16,0.000,1.000,0.000,0.0000,0.000,0.932,0.068,0.3400
3,Google misled consumers over data collection -...,SYDNEY (Reuters) -Australia's federal court fo...,2021-04-16,0.000,1.000,0.000,0.0000,0.000,1.000,0.000,0.0000
4,"With flagship electric car, Mercedes takes fig...","Daimler AG on Thursday unveiled the electric ""...",2021-04-16,0.236,0.636,0.127,-0.2960,0.134,0.773,0.093,-0.3818
...,...,...,...,...,...,...,...,...,...,...,...
49672,Cambridge Analytica played key Trump campaign ...,The suspended chief executive of UK-based poli...,2018-03-20,0.000,0.806,0.194,0.3400,0.079,0.812,0.109,0.0516
49673,"Factbox: How United States, others regulate au...",An Uber self-driving sport utility vehicle str...,2018-03-20,0.000,0.741,0.259,0.4215,0.268,0.732,0.000,-0.9001
49674,Senate Democrat wants Facebook CEO Zuckerberg ...,"U.S. Senator Dianne Feinstein, the top Democra...",2018-03-20,0.000,1.000,0.000,0.0000,0.000,0.945,0.055,0.2023
49675,Factbox: Who is Cambridge Analytica and what d...,British data analytics firm Cambridge Analytic...,2018-03-20,0.000,1.000,0.000,0.0000,0.000,0.926,0.074,0.4215
49676,UK will always consider ways to improve data l...,Britain will consider any suggestions to give ...,2018-03-20,0.000,0.791,0.209,0.4404,0.000,0.925,0.075,0.4404

In [7]:
description_sentiment

0        {'neg': 0.138, 'neu': 0.811, 'pos': 0.052, 'co...
1        {'neg': 0.224, 'neu': 0.603, 'pos': 0.172, 'co...
2        {'neg': 0.0, 'neu': 0.932, 'pos': 0.068, 'comp...
3        {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
4        {'neg': 0.134, 'neu': 0.773, 'pos': 0.093, 'co...
                               ...
49672    {'neg': 0.079, 'neu': 0.812, 'pos': 0.109, 'co...
49673    {'neg': 0.268, 'neu': 0.732, 'pos': 0.0, 'comp...
49674    {'neg': 0.0, 'neu': 0.945, 'pos': 0.055, 'comp...
49675    {'neg': 0.0, 'neu': 0.926, 'pos': 0.074, 'comp...
49676    {'neg': 0.0, 'neu': 0.925, 'pos': 0.075, 'comp...
Name: description, Length: 49677, dtype: object

In [8]:
reuters_data.to_csv('reuters_sentiment.csv')

In [9]:
pure_sentiment = reuters_data.drop(columns=['title','description'])
pure_sentiment

,date,neg,neu,pos,compound,neg_description,neu_description,pos_description,compound_description
0,2021-04-16,0.272,0.728,0.000,-0.6808,0.138,0.811,0.052,-0.5423
1,2021-04-16,0.224,0.603,0.172,-0.1531,0.224,0.603,0.172,-0.1531
2,2021-04-16,0.000,1.000,0.000,0.0000,0.000,0.932,0.068,0.3400
3,2021-04-16,0.000,1.000,0.000,0.0000,0.000,1.000,0.000,0.0000
4,2021-04-16,0.236,0.636,0.127,-0.2960,0.134,0.773,0.093,-0.3818
...,...,...,...,...,...,...,...,...,...
49672,2018-03-20,0.000,0.806,0.194,0.3400,0.079,0.812,0.109,0.0516
49673,2018-03-20,0.000,0.741,0.259,0.4215,0.268,0.732,0.000,-0.9001
49674,2018-03-20,0.000,1.000,0.000,0.0000,0.000,0.945,0.055,0.2023
49675,2018-03-20,0.000,1.000,0.000,0.0000,0.000,0.926,0.074,0.4215
49676,2018-03-20,0.000,0.791,0.209,0.4404,0.000,0.925,0.075,0.4404

In [10]:
dates = pure_sentiment['date'].drop_duplicates().values
dates

array(['2021-04-16', '2021-04-15', '2021-04-14', ..., '2018-03-22',
       '2018-03-21', '2018-03-20'], dtype=object)

In [11]:
daily_sentiment = [pure_sentiment.loc[pure_sentiment['date'] == date] for date in dates]
# daily_sentiment

In [30]:
first_sample = daily_sentiment[0]
# first_sample

In [13]:
mean_first_sample

neg                     0.092604
neu                     0.793604
pos                     0.113792
compound                0.025758
neg_description         0.069083
neu_description         0.842917
pos_description         0.087979
compound_description    0.067115
dtype: float64

In [33]:
mean_daily_sentiment = daily_sentiment.copy()
for i in range(0,len(daily_sentiment)):
    mean_daily_sentiment[i] = daily_sentiment[i].mean()
    
# mean_daily_sentiment

In [18]:
daily_sentiment_average = pd.DataFrame(dates)
daily_sentiment_average = daily_sentiment_average.join(pd.DataFrame(mean_daily_sentiment), how='right')
daily_sentiment_average

,0,neg,neu,pos,compound,neg_description,neu_description,pos_description,compound_description
0,2021-04-16,0.092604,0.793604,0.113792,0.025758,0.069083,0.842917,0.087979,0.067115
1,2021-04-15,0.062340,0.840470,0.097190,0.053673,0.054310,0.856250,0.089450,0.156695
2,2021-04-14,0.098358,0.817979,0.083674,-0.026956,0.064200,0.859800,0.076021,0.104177
3,2021-04-13,0.052677,0.869277,0.078015,0.051142,0.056985,0.867354,0.075646,0.106286
4,2021-04-12,0.049151,0.837890,0.112959,0.094377,0.059178,0.864027,0.076808,0.040249
...,...,...,...,...,...,...,...,...,...
1118,2018-03-24,0.101455,0.806364,0.092182,0.005636,0.070364,0.861818,0.067818,-0.077764
1119,2018-03-23,0.101315,0.801315,0.097370,-0.011381,0.063222,0.843093,0.093704,0.155633
1120,2018-03-22,0.117712,0.794685,0.087616,-0.034803,0.063425,0.859425,0.077082,0.056668
1121,2018-03-21,0.076710,0.839177,0.084113,0.014061,0.047355,0.875855,0.076774,0.115885
1122,2018-03-20,0.104179,0.824286,0.071554,-0.053068,0.073179,0.859768,0.067054,-0.030854

In [27]:
columns = ['date', 'title_neg', 'title_neu', 'title_pos', 'title_compound', 'desc_neg', 'desc_neu', 'desc_pos', 'desc_compound']
daily_sentiment_average.columns = columns
daily_sentiment_average.set_index('date', inplace=True)
daily_sentiment_average

,title_neg,title_neu,title_pos,title_compound,desc_neg,desc_neu,desc_pos,desc_compound
date,,,,,,,,
2021-04-16,0.092604,0.793604,0.113792,0.025758,0.069083,0.842917,0.087979,0.067115
2021-04-15,0.062340,0.840470,0.097190,0.053673,0.054310,0.856250,0.089450,0.156695
2021-04-14,0.098358,0.817979,0.083674,-0.026956,0.064200,0.859800,0.076021,0.104177
2021-04-13,0.052677,0.869277,0.078015,0.051142,0.056985,0.867354,0.075646,0.106286
2021-04-12,0.049151,0.837890,0.112959,0.094377,0.059178,0.864027,0.076808,0.040249
...,...,...,...,...,...,...,...,...
2018-03-24,0.101455,0.806364,0.092182,0.005636,0.070364,0.861818,0.067818,-0.077764
2018-03-23,0.101315,0.801315,0.097370,-0.011381,0.063222,0.843093,0.093704,0.155633
2018-03-22,0.117712,0.794685,0.087616,-0.034803,0.063425,0.859425,0.077082,0.056668
2018-03-21,0.076710,0.839177,0.084113,0.014061,0.047355,0.875855,0.076774,0.115885
2018-03-20,0.104179,0.824286,0.071554,-0.053068,0.073179,0.859768,0.067054,-0.030854

In [28]:
daily_sentiment_average.to_csv('daily_sentiments.csv')

### Now to use the data

In order to see if the sentiment can be used to predict returns I want to feed the returns data and compare.

In [ ]:
returns =