## Investigating The Performance of the S&P500

In [9]:
import pandas as pd

In [59]:
sp500 = pd.read_csv('../data/indices/yahoo/gspc.csv', parse_dates=True, index_col=0).sort_index(ascending=True)
sp500

,Open,High,Low,Close (split adjusted),Adj Close(dividends and splits),Volume
Date,,,,,,
2018-02-28,2753.78,2761.52,2713.54,2713.83,2713.83,4230660000
2018-03-01,2715.22,2730.89,2659.65,2677.67,2677.67,4503970000
2018-03-02,2658.89,2696.25,2647.32,2691.25,2691.25,3882450000
2018-03-05,2681.06,2728.09,2675.75,2720.94,2720.94,3710810000
2018-03-06,2730.18,2732.08,2711.26,2728.12,2728.12,3370690000
...,...,...,...,...,...,...
2021-04-12,4124.71,4131.76,4114.82,4127.99,4127.99,3578500000
2021-04-13,4130.10,4148.00,4124.43,4141.59,4141.59,3728440000
2021-04-14,4141.58,4151.69,4120.87,4124.66,4124.66,3976540000
2021-04-15,4139.76,4173.49,4139.76,4170.42,4170.42,4027680000
2021-04-16,4174.14,4191.31,4170.75,4185.47,4185.47,4157430000

# Goals

I need to have data that is useful when analysing the news sentiment. It would be productive to offer a module that would provide data on:

* Returns 
    * Look at the % between adj close of two days
    * Difference from adj close to the open price
    
* Market Action
    * Volatility
    * Volume
    * Trading range
    
* Drawdowns
    * Look at investment_management/1/103
    
* Other statistical measures
    * https://docs.scipy.org/doc/scipy/reference/stats.html (or the later courses in investment management)
    

Through doing this I should also think about how (if) I take the effect of a weekend into account. Can take a look at if returns on Monday are different enough.

### Returns

In [13]:
returns = sp500[['Open', 'Adj Close(dividends and splits)']]
returns['Change'] = sp500[['Adj Close(dividends and splits)']].pct_change()
returns

<ipython-input-13-aaf3d9d00e18>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  returns['Change'] = sp500[['Adj Close(dividends and splits)']].pct_change()

               Open  Adj Close(dividends and splits)    Change
Date
2018-02-28  2753.78                          2713.83       NaN
2018-03-01  2715.22                          2677.67 -0.013324
2018-03-02  2658.89                          2691.25  0.005072
2018-03-05  2681.06                          2720.94  0.011032
2018-03-06  2730.18                          2728.12  0.002639
...             ...                              ...       ...
2021-04-12  4124.71                          4127.99 -0.000196
2021-04-13  4130.10                          4141.59  0.003295
2021-04-14  4141.58                          4124.66 -0.004088
2021-04-15  4139.76                          4170.42  0.011094
2021-04-16  4174.14                          4185.47  0.003609

[789 rows x 3 columns]

In [25]:
# Not sure how to do this nicely in pandas, pretty hacky
import numpy as np

close_to_open = []
close_to_open.append(np.nan)

for i in range (1, len(returns)):
    previous_close = returns.iloc[int(i) - 1]['Adj Close(dividends and splits)']
    open_price = returns.iloc[i]['Open']
    close_to_open.append((open_price-previous_close)/previous_close)

In [26]:
returns['Close to Open Change'] = close_to_open

<ipython-input-26-38268947712f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  returns['Close to Open Change'] = close_to_open

In [27]:
returns

,Open,Adj Close(dividends and splits),Change,Close to Open Change
Date,,,,
2018-02-28,2753.78,2713.83,NaN,NaN
2018-03-01,2715.22,2677.67,-0.013324,0.000512
2018-03-02,2658.89,2691.25,0.005072,-0.007014
2018-03-05,2681.06,2720.94,0.011032,-0.003786
2018-03-06,2730.18,2728.12,0.002639,0.003396
...,...,...,...,...
2021-04-12,4124.71,4127.99,-0.000196,-0.000991
2021-04-13,4130.10,4141.59,0.003295,0.000511
2021-04-14,4141.58,4124.66,-0.004088,-0.000002
2021-04-15,4139.76,4170.42,0.011094,0.003661
2021-04-16,4174.14,4185.47,0.003609,0.000892

In [33]:
returns = returns[1:]
returns

,Open,Adj Close(dividends and splits),Change,Close to Open Change
Date,,,,
2018-03-01,2715.22,2677.67,-0.013324,0.000512
2018-03-02,2658.89,2691.25,0.005072,-0.007014
2018-03-05,2681.06,2720.94,0.011032,-0.003786
2018-03-06,2730.18,2728.12,0.002639,0.003396
2018-03-07,2710.18,2726.80,-0.000484,-0.006576
...,...,...,...,...
2021-04-12,4124.71,4127.99,-0.000196,-0.000991
2021-04-13,4130.10,4141.59,0.003295,0.000511
2021-04-14,4141.58,4124.66,-0.004088,-0.000002
2021-04-15,4139.76,4170.42,0.011094,0.003661
2021-04-16,4174.14,4185.47,0.003609,0.000892

In [36]:
returns.to_csv('../data/calculations/returns.csv')

### Market Action

In [37]:
sp500.columns

Index(['Open', 'High', 'Low', 'Close (split adjusted)',
       'Adj Close(dividends and splits)', 'Volume'],
      dtype='object')

#### Volatility
I was thinking about taking the volatility of the entire period by I did'nt want the look-ahead error.

In [61]:
rolling_30_avg = sp500['Adj Close(dividends and splits)'].rolling(30).mean()
rolling_30_avg

Date
2018-02-28            NaN
2018-03-01            NaN
2018-03-02            NaN
2018-03-05            NaN
2018-03-06            NaN
                 ...
2021-04-12    3951.577333
2021-04-13    3959.569667
2021-04-14    3968.048667
2021-04-15    3979.738667
2021-04-16    3993.638667
Name: Adj Close(dividends and splits), Length: 789, dtype: float64

In [74]:
market_action = sp500[['Volume','Adj Close(dividends and splits)']]
market_action['30D avg price'] = rolling_30_avg
market_action

<ipython-input-74-e6cdfa0e68cb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  market_action['30D avg price'] = rolling_30_avg

                Volume  Adj Close(dividends and splits)  30D avg price
Date
2018-02-28  4230660000                          2713.83            NaN
2018-03-01  4503970000                          2677.67            NaN
2018-03-02  3882450000                          2691.25            NaN
2018-03-05  3710810000                          2720.94            NaN
2018-03-06  3370690000                          2728.12            NaN
...                ...                              ...            ...
2021-04-12  3578500000                          4127.99    3951.577333
2021-04-13  3728440000                          4141.59    3959.569667
2021-04-14  3976540000                          4124.66    3968.048667
2021-04-15  4027680000                          4170.42    3979.738667
2021-04-16  4157430000                          4185.47    3993.638667

[789 rows x 3 columns]

In [81]:
deviation = market_action['30D avg price'] - market_action['Adj Close(dividends and splits)']
market_action['Deviation'] = deviation

In [84]:
market_action['Deviation^2'] = deviation ** 2

In [86]:
market_action['30D Variance'] = market_action['Deviation^2'].rolling(30).mean()

In [87]:
market_action['Std Deviation'] = market_action['30D Variance'] ** 0.5

In [93]:
market_action.head(60)

,Volume,Adj Close(dividends and splits),30D avg price,Deviation,Deviation^2,30D Variance,Std Deviation
Date,,,,,,,
2018-02-28,4230660000,2713.83,NaN,NaN,NaN,NaN,NaN
2018-03-01,4503970000,2677.67,NaN,NaN,NaN,NaN,NaN
2018-03-02,3882450000,2691.25,NaN,NaN,NaN,NaN,NaN
2018-03-05,3710810000,2720.94,NaN,NaN,NaN,NaN,NaN
2018-03-06,3370690000,2728.12,NaN,NaN,NaN,NaN,NaN
2018-03-07,3393270000,2726.80,NaN,NaN,NaN,NaN,NaN
2018-03-08,3212320000,2738.97,NaN,NaN,NaN,NaN,NaN
2018-03-09,3364100000,2786.57,NaN,NaN,NaN,NaN,NaN
2018-03-12,3185020000,2783.02,NaN,NaN,NaN,NaN,NaN
2018-03-13,3301650000,2765.31,NaN,NaN,NaN,NaN,NaN
2018-03-14,3391360000,2749.48,NaN,NaN,NaN,NaN,NaN
2018-03-15,3500330000,2747.33,NaN,NaN,NaN,NaN,NaN
2018-03-16,5372340000,2752.01,NaN,NaN,NaN,NaN,NaN
2018-03-19,3302130000,2712.92,NaN,NaN,NaN,NaN,NaN
2018-03-20,3261030000,2716.94,NaN,NaN,NaN,NaN,NaN
2018-03-21,3415510000,2711.93,NaN,NaN,NaN,NaN,NaN
2018-03-22,3739800000,2643.69,NaN,NaN,NaN,NaN,NaN
2018-03-23,3815080000,2588.26,NaN,NaN,NaN,NaN,NaN
2018-03-26,3511100000,2658.55,NaN,NaN,NaN,NaN,NaN
2018-03-27,3706350000,2612.62,NaN,NaN,NaN,NaN,NaN
2018-03-28,3864500000,2605.00,NaN,NaN,NaN,NaN,NaN
2018-03-29,3565990000,2640.87,NaN,NaN,NaN,NaN,NaN
2018-04-02,3598520000,2581.88,NaN,NaN,NaN,NaN,NaN
2018-04-03,3392810000,2614.45,NaN,NaN,NaN,NaN,NaN
2018-04-04,3350340000,2644.69,NaN,NaN,NaN,NaN,NaN
2018-04-05,3178970000,2662.84,NaN,NaN,NaN,NaN,NaN
2018-04-06,3299700000,2604.47,NaN,NaN,NaN,NaN,NaN
2018-04-09,3062960000,2613.16,NaN,NaN,NaN,NaN,NaN
2018-04-10,3543930000,2656.87,NaN,NaN,NaN,NaN,NaN
2018-04-11,3020760000,2642.19,2683.087667,40.897667,1672.619139,NaN,NaN
2018-04-12,3021320000,2663.99,2681.426333,17.436333,304.025720,NaN,NaN
2018-04-13,2960910000,2656.30,2680.714000,24.414000,596.043396,NaN,NaN
2018-04-16,3019700000,2677.84,2680.267000,2.427000,5.890329,NaN,NaN
2018-04-17,3234360000,2706.39,2679.782000,-26.608000,707.985664,NaN,NaN
2018-04-18,3383410000,2708.64,2679.132667,-29.507333,870.682720,NaN,NaN
2018-04-19,3349370000,2693.13,2678.010333,-15.119667,228.604320,NaN,NaN
2018-04-20,3388590000,2670.14,2675.716000,5.576000,31.091776,NaN,NaN
2018-04-23,3017480000,2670.29,2671.840000,1.550000,2.402500,NaN,NaN
2018-04-24,3706740000,2634.56,2666.891333,32.331333,1045.315115,NaN,NaN
2018-04-25,3499440000,2639.40,2662.694333,23.294333,542.625965,NaN,NaN
2018-04-26,3665720000,2666.94,2659.943000,-6.997000,48.958009,NaN,NaN
2018-04-27,3219030000,2669.91,2657.362333,-12.547667,157.443939,NaN,NaN
2018-04-30,3734530000,2648.05,2653.897000,5.847000,34.187409,NaN,NaN
2018-05-01,3559850000,2654.80,2651.959667,-2.840333,8.067493,NaN,NaN
2018-05-02,4010770000,2635.67,2649.250667,13.580667,184.434507,NaN,NaN
2018-05-03,3851470000,2629.73,2646.510667,16.780667,281.590774,NaN,NaN
2018-05-04,3327220000,2663.42,2647.168333,-16.251667,264.116669,NaN,NaN
2018-05-07,3237960000,2672.63,2649.980667,-22.649333,512.992300,NaN,NaN
2018-05-08,3717570000,2671.92,2650.426333,-21.493667,461.977707,NaN,NaN
2018-05-09,3909500000,2697.79,2653.265333,-44.524667,1982.445942,NaN,NaN
2018-05-10,3333050000,2723.07,2657.201000,-65.869000,4338.725161,NaN,NaN
2018-05-11,2862700000,2727.72,2660.096000,-67.624000,4573.005376,NaN,NaN
2018-05-14,2972660000,2730.13,2665.037667,-65.092333,4237.011859,NaN,NaN
2018-05-15,3290680000,2711.45,2668.271000,-43.179000,1864.426041,NaN,NaN
2018-05-16,3202670000,2722.46,2670.863333,-51.596667,2662.216011,NaN,NaN
2018-05-17,3475400000,2720.13,2672.773000,-47.357000,2242.685449,NaN,NaN
2018-05-18,3368690000,2712.97,2676.389667,-36.580333,1338.120787,NaN,NaN
2018-05-21,3019890000,2733.01,2680.384667,-52.625333,2769.425708,NaN,NaN
2018-05-22,3366310000,2724.44,2682.637000,-41.803000,1747.490809,1190.553620,34.50440
2018-05-23,3326290000,2733.29,2685.673667,-47.616333,2267.315200,1210.376822,34.79047

In [94]:
market_action['2020-03-01':'2020-03-31']

,Volume,Adj Close(dividends and splits),30D avg price,Deviation,Deviation^2,30D Variance,Std Deviation
Date,,,,,,,
2020-03-02,6376400000,3090.23,3275.160667,184.930667,34199.351474,13845.397852,117.666469
2020-03-03,6355940000,3003.37,3264.285667,260.915667,68076.985112,15730.513304,125.421343
2020-03-04,5035480000,3130.12,3257.930000,127.810000,16335.396100,15994.491703,126.469331
2020-03-05,5575550000,3023.94,3248.003000,224.063000,50204.227969,17416.606624,131.971992
2020-03-06,6552140000,2972.37,3236.230667,263.860667,69622.451414,19500.425169,139.643923
2020-03-09,8423050000,2746.56,3217.933667,471.373667,222193.133627,26827.459933,163.790903
2020-03-10,7635960000,2882.23,3205.887000,323.657000,104753.853649,30317.875462,174.120290
2020-03-11,7374110000,2741.38,3188.058333,446.678333,199521.533469,36951.586488,192.227954
2020-03-12,8829380000,2480.64,3161.633000,680.993000,463751.466049,52401.154685,228.912985
2020-03-13,8258670000,2711.02,3142.545000,431.525000,186213.825625,58589.956292,242.053623
2020-03-16,7781540000,2386.13,3114.565333,728.435333,530618.034848,76234.520287,276.105995
2020-03-17,8358500000,2529.19,3090.574333,561.384333,315152.369712,86732.765137,294.504270
2020-03-18,8755780000,2398.10,3060.591333,662.491333,438894.766742,101329.981642,318.323706
2020-03-19,7946710000,2409.39,3029.748000,620.358000,384844.048164,114019.032780,337.667044
2020-03-20,9044690000,2304.92,2995.052667,690.132667,476283.097600,129724.126571,360.172357
2020-03-23,7402180000,2237.40,2958.709000,721.309000,520286.673481,146983.421038,383.384169
2020-03-24,7547350000,2447.33,2928.550333,481.220333,231573.009213,154535.815446,393.110437
2020-03-25,8285670000,2475.56,2899.144000,423.584000,179423.405056,160341.606324,400.426780
2020-03-26,7753160000,2630.07,2874.164667,244.094667,59582.206295,162064.342253,402.572158
2020-03-27,6194330000,2541.47,2846.415667,304.945667,92991.859619,164958.135414,406.150385
2020-03-30,5746220000,2626.65,2821.298667,194.648667,37888.103435,166003.754205,407.435583
2020-03-31,6568290000,2584.59,2795.108667,210.518667,44318.109015,167334.240609,409.065081