## Investigating The Performance of the S&P500

In [9]:
import pandas as pd

In [10]:
sp500 = pd.read_csv('../data/indices/yahoo/gspc.csv', parse_dates=True, index_col=0).sort_index(ascending=True)
sp500

,Open,High,Low,Close (split adjusted),Adj Close(dividends and splits),Volume
Date,,,,,,
2018-02-28,2753.78,2761.52,2713.54,2713.83,2713.83,4230660000
2018-03-01,2715.22,2730.89,2659.65,2677.67,2677.67,4503970000
2018-03-02,2658.89,2696.25,2647.32,2691.25,2691.25,3882450000
2018-03-05,2681.06,2728.09,2675.75,2720.94,2720.94,3710810000
2018-03-06,2730.18,2732.08,2711.26,2728.12,2728.12,3370690000
...,...,...,...,...,...,...
2021-04-12,4124.71,4131.76,4114.82,4127.99,4127.99,3578500000
2021-04-13,4130.10,4148.00,4124.43,4141.59,4141.59,3728440000
2021-04-14,4141.58,4151.69,4120.87,4124.66,4124.66,3976540000
2021-04-15,4139.76,4173.49,4139.76,4170.42,4170.42,4027680000
2021-04-16,4174.14,4191.31,4170.75,4185.47,4185.47,4157430000

# Goals

I need to have data that is useful when analysing the news sentiment. It would be productive to offer a module that would provide data on:

* Returns 
    * Look at the % between adj close of two days
    * Difference from adj close to the open price
    
* Market Action
    * Volatility
    * Volume
    * Trading range
    
* Drawdowns
    * Look at investment_management/1/103
    
* Other statistical measures
    * https://docs.scipy.org/doc/scipy/reference/stats.html (or the later courses in investment management)
    

Through doing this I should also think about how (if) I take the effect of a weekend into account. Can take a look at if returns on Monday are different enough.

### Returns

In [13]:
returns = sp500[['Open', 'Adj Close(dividends and splits)']]
returns['Change'] = sp500[['Adj Close(dividends and splits)']].pct_change()
returns

<ipython-input-13-aaf3d9d00e18>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  returns['Change'] = sp500[['Adj Close(dividends and splits)']].pct_change()

               Open  Adj Close(dividends and splits)    Change
Date
2018-02-28  2753.78                          2713.83       NaN
2018-03-01  2715.22                          2677.67 -0.013324
2018-03-02  2658.89                          2691.25  0.005072
2018-03-05  2681.06                          2720.94  0.011032
2018-03-06  2730.18                          2728.12  0.002639
...             ...                              ...       ...
2021-04-12  4124.71                          4127.99 -0.000196
2021-04-13  4130.10                          4141.59  0.003295
2021-04-14  4141.58                          4124.66 -0.004088
2021-04-15  4139.76                          4170.42  0.011094
2021-04-16  4174.14                          4185.47  0.003609

[789 rows x 3 columns]